language: java
jdk:
    - openjdk6
    - openjdk7
    - oraclejdk7
matrix:
    include:
        - jdk: oraclejdk8
          script:
              - java -Xms2G -Xmx2G -jar ForgeBuilder/target/*.jar -s1.6.4 -s1.5.2 -s1.4.7 -s1.4.5 QuarryPlus
install:
    - cd ..
    - git clone --depth 1 git://github.com/yogpstop/ForgeBuilder
    - cd ForgeBuilder
    - mvn package -q -Dmaven.test.skip=true
    - cd ..
script:
    - bash ForgeBuilder/src/main/sh/bc.sh ForgeBuilder/target/*.jar
    - java -Xms2G -Xmx2G -jar ForgeBuilder/target/*.jar QuarryPlus
env:
    global:
        - REL_TYPE='CI'
